# .github/workflows/main.yml
name: CI/CD Spring Boot App Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2    

      - name: Set Up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'      

      - name: Build with Maven
        run: |                   
          mvn clean package -DskipTests
          
      - name: Install Java 8 on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo yum install -y java-1.8.0-openjdk
            
      - name: Transfer JAR1 to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./gatewayservice/target/gatewayservice-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user"
          
      - name: Transfer JAR2 to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./counterservice/target/counterservice-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user"
          
      - name: Transfer JAR3 to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./configservice/target/configservice-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user"
          
          
      - name: Transfer JAR4 to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./registryservice/target/registryservice-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user"
          
          
      - name: Transfer JAR5 to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./docker-compose.yml"
          target: "/home/ec2-user"
       

     
